name: CI/CD runner

on:
  push:
    branches:
      - master
      - develop
      - feature/github-actions

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install
        env:
          FONTAWESOME_PACKAGE_TOKEN: ${{ secrets.FONTAWESOME_PACKAGE_TOKEN }}
        run: npm ci

      - name: Lint test
        run: npm run test:eslint

      - name: Unit test
        run: npm run test:unit
